"""
HTTP Status Code Constants for the application.
These constants are loaded from environment variables.
"""

import os

from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# HTTP Status Code Constants
HTTP_STATUS_OK = int(os.getenv("HTTP_STATUS_OK", "200"))
HTTP_STATUS_CREATED = int(os.getenv("HTTP_STATUS_CREATED", "201"))
HTTP_STATUS_ACCEPTED = int(os.getenv("HTTP_STATUS_ACCEPTED", "202"))
HTTP_STATUS_NO_CONTENT = int(os.getenv("HTTP_STATUS_NO_CONTENT", "204"))
HTTP_STATUS_BAD_REQUEST = int(os.getenv("HTTP_STATUS_BAD_REQUEST", "400"))
HTTP_STATUS_UNAUTHORIZED = int(os.getenv("HTTP_STATUS_UNAUTHORIZED", "401"))
HTTP_STATUS_FORBIDDEN = int(os.getenv("HTTP_STATUS_FORBIDDEN", "403"))
HTTP_STATUS_NOT_FOUND = int(os.getenv("HTTP_STATUS_NOT_FOUND", "404"))
HTTP_STATUS_METHOD_NOT_ALLOWED = int(os.getenv("HTTP_STATUS_METHOD_NOT_ALLOWED", "405"))
HTTP_STATUS_REQUEST_TIMEOUT = int(os.getenv("HTTP_STATUS_REQUEST_TIMEOUT", "408"))
HTTP_STATUS_CONFLICT = int(os.getenv("HTTP_STATUS_CONFLICT", "409"))
HTTP_STATUS_UNPROCESSABLE_ENTITY = int(
    os.getenv("HTTP_STATUS_UNPROCESSABLE_ENTITY", "422")
)
HTTP_STATUS_INTERNAL_SERVER_ERROR = int(
    os.getenv("HTTP_STATUS_INTERNAL_SERVER_ERROR", "500")
)
HTTP_STATUS_BAD_GATEWAY = int(os.getenv("HTTP_STATUS_BAD_GATEWAY", "502"))
HTTP_STATUS_SERVICE_UNAVAILABLE = int(
    os.getenv("HTTP_STATUS_SERVICE_UNAVAILABLE", "503")
)
HTTP_STATUS_GATEWAY_TIMEOUT = int(os.getenv("HTTP_STATUS_GATEWAY_TIMEOUT", "504"))

# Commonly used status codes grouped for convenience
SUCCESS_CODES = [
    HTTP_STATUS_OK,
    HTTP_STATUS_CREATED,
    HTTP_STATUS_ACCEPTED,
    HTTP_STATUS_NO_CONTENT,
]
CLIENT_ERROR_CODES = [
    HTTP_STATUS_BAD_REQUEST,
    HTTP_STATUS_UNAUTHORIZED,
    HTTP_STATUS_FORBIDDEN,
    HTTP_STATUS_NOT_FOUND,
    HTTP_STATUS_METHOD_NOT_ALLOWED,
    HTTP_STATUS_REQUEST_TIMEOUT,
    HTTP_STATUS_CONFLICT,
    HTTP_STATUS_UNPROCESSABLE_ENTITY,
]
SERVER_ERROR_CODES = [
    HTTP_STATUS_INTERNAL_SERVER_ERROR,
    HTTP_STATUS_BAD_GATEWAY,
    HTTP_STATUS_SERVICE_UNAVAILABLE,
    HTTP_STATUS_GATEWAY_TIMEOUT,
]
