name: legal_assistant
channels:
  - pytorch
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2

dependencies:
  - python=3.12
  - pip
  - requests=2.32.4
  - beautifulsoup4=4.13.4
  - lxml=5.4.0
  - sentence-transformers=4.1.0
  - pytorch=2.5.1
  - transformers=4.52.4
  - fastapi=0.115.12
  - uvicorn=0.34.3
  - python-dotenv=1.1.0
  - aiohttp=3.12.12
  - pandas=2.3.0
  - numpy=2.3.0
  - black=25.1.0
  - isort=6.0.1
  - pylint=3.3.7

  - pip:
      - google-generativeai==0.8.5
